---
title: "Fog Detection"
author: "Martin Roth and Andrea Pagani"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Fog Detection}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  fig.width  = 7,
  fig.height = 4
)
```

## Example how to use visDec
### Load required libaries
```{r, message=FALSE}
library(imager)
library(data.table)
library(ggplot2)
library(data.table)
library(visDec)
library(changepoint)
library(foreach)
library(iterators)
library(doParallel)
registerDoParallel(cores=2)
```

### Read example pictures
```{r, ExamplePictures}
path <- "../inst/extdata/Meetterrein"
path2 <- "/net/bhw420/nobackup/users/wauben/CAMERA/EHTW/201510"
filenames <- list.files(path2,
                        #pattern=glob2rx("Meetterrein_201510*.jpg"),
                        pattern=glob2rx("EHTW_2015102109*.jpg"),
                        full.names=TRUE)
```

```{r, ComputeEdgesClear, echo=FALSE}
detect.edges <- function(im,sigma=1) {
  # adapted from http://dahtah.github.io/imager/foreground_background.html
  isoblur(im,sigma) %>% imgradient("xy") %>% llply(function(v) v^2) %>%
    add %>% imsplit("c") %>% add 
}
```

### Edges in a clear situation
```{r, EdgesPlotFoggy, echo=FALSE}
im <- subim(load.image(filenames[75]), y > 16)
old_par <- par(mfrow=c(1,2))
plot(im)
detect.edges(im) %>% sqrt %>% plot
par(old_par)
```

### Edges in a foggy situation
```{r, EdgesPlotClear, echo=FALSE}
im <- subim(load.image(filenames[49]), y > 16)
old_par <- par(mfrow=c(1,2))
plot(im)
detect.edges(im) %>% sqrt %>% plot
par(old_par)
```

### Computing basis image statistics

```{r, imageSummary}
imageSummary <- foreach(file = iter(filenames), .combine = rbind) %dopar% {
  FileNameParser(file, "na*me_yyyymmddhhmm.jpg")#Twente pattern
}

daylightImages <- FilterDayLightHours(imageSummary)[isDay == TRUE]


ReturnFeatures <- function(filePath) {
  im <- subim(load.image(filePath), y > 16) 
  imT <- RGBtoHSV(im)
  list(meanEdge = detect.edges(im, 3) %>% sqrt %>% mean,
       changePoint = cpts(cpt.mean(GetHorizAvgTrans(im), penalty = "None")),
       meanHue = mean(channel(imT, 1)),
       meanSaturation = mean(channel(imT, 2)),
       meanBrightness = mean(channel(imT, 3)) )
}

featureNames <- c("meanEdge", "changePoint", "meanHue", "meanSaturation",
                  "meanBrightness")


daylightImages[, id := 1:.N]
setkey(daylightImages, id)

imageSummary <- foreach(id = iter(daylightImages[, id]), .packages = c('data.table'), .combine = rbind) %dopar% {
  tmp <- daylightImages[id, ]
  tmp[, eval(featureNames) := ReturnFeatures(filePath), by = dateTime]
}

```



### Load sensor values -- Twente
```{r, SensorFiles, fig.show='hold'}
sensorFiles <- list.files("../inst/extdata/Sensor",
                          pattern=glob2rx("Twente*.csv"),
                          full.names=TRUE)
sensorData <- ReadMORSensorDataTWE(sensorFiles)
setkey(sensorData, dateTime)
setkey(imageSummary, dateTime)
imageSummary <- merge(imageSummary, sensorData)
imageSummary[, MOR := TOA.MOR_10, by = dateTime]
```





### Time series
```{r, TimeSeries, fig.show='hold'}
ggplot(imageSummary, aes(x = dateTime, y = meanEdge)) + geom_line() + xlab("")
ggplot(imageSummary, aes(x = dateTime, y= MOR)) + geom_line() +
  xlab("") 
```

```{r, DayOnly, fig.show='hold'}
ggplot(imageSummary[hour(dateTime) %in% seq(5, 10, by=1), ],
       aes(x = dateTime, y = meanEdge)) + geom_line() + xlab("")
```


### Scatter plots
```{r, ScatterPlots, fig.show='hold'}
imageSummary[, visibility := factor(2000)]
imageSummary[MOR < 1000, visibility := factor(1000)]
imageSummary[MOR < 500, visibility := factor(500)]
imageSummary[MOR < 200, visibility := factor(200)]
ggplot(imageSummary[hour %in% seq(7, 16, by = 1), ], aes(x = log(MOR), y = meanEdge, col = visibility)) + geom_point()
ggplot(imageSummary[hour %in% seq(7, 16, by = 1), ], aes(x = log(MOR), y = meanEdge, col = visibility)) + geom_point() + geom_quantile(aes(col=NULL), quantiles=0.5)
ggplot(imageSummary[hour %in% seq(7, 16, by = 1), ], aes(x = log(MOR), y = changePoint, col = visibility)) + geom_point() + geom_quantile(aes(col=NULL), quantiles=0.5)
ggplot(imageSummary[hour %in% seq(7, 16, by = 1), ], aes(x = log(MOR), y = meanHue, col = visibility)) + geom_point() + geom_quantile(aes(col=NULL), quantiles=0.5)
ggplot(imageSummary[hour %in% seq(7, 16, by = 1), ], aes(x = log(MOR), y = meanSaturation, col = visibility)) + geom_point() + geom_quantile(aes(col=NULL), quantiles=0.5)
ggplot(imageSummary[hour %in% seq(7, 16, by = 1), ], aes(x = log(MOR), y = meanBrightness, col = visibility)) + geom_point() + geom_quantile(aes(col=NULL), quantiles=0.5)
```

```{r, echo=FALSE}
stopImplicitCluster()
```
