// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// PointAnalyser
void PointAnalyser(const std::string filename);
RcppExport SEXP visDec_PointAnalyser(SEXP filenameSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const std::string >::type filename(filenameSEXP);
    PointAnalyser(filename);
    return R_NilValue;
END_RCPP
}
